# Generated by Django 5.0.14 on 2026-03-04 00:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoPremios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_premio', models.CharField(max_length=150)),
                ('costo_puntos', models.IntegerField(help_text='Cuántos puntos cuesta canjear este premio')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteFidelidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(help_text='Para buscar rápido en caja', max_length=20, unique=True)),
                ('pin_seguridad', models.CharField(help_text='PIN 4 dígitos para portal del cliente', max_length=4)),
                ('puntos_actuales', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMovimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SUMA', 'Acumulación de Puntos'), ('CANJE', 'Canje de Premio'), ('AJUSTE', 'Ajuste Manual')], max_length=20)),
                ('puntos_involucrados', models.IntegerField(help_text='Positivos o negativos')),
                ('nota_cajero', models.CharField(blank=True, help_text='Ej: Compra Ticket #1024 o Canje Pastel', max_length=255, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='panaderia.clientefidelidad')),
            ],
        ),
    ]
