# Generated by Django 5.0.14 on 2026-03-04 00:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPanaderia',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador General'), ('CAJERO', 'Cajero de Mostrador')], default='CAJERO', max_length=20)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('pin_seguridad', models.CharField(help_text='PIN rápido 4 dígitos', max_length=4)),
                ('foto_perfil', models.CharField(blank=True, help_text='URL o path de la foto', max_length=255, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Activado Lógico')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, help_text='Fecha de inicio del trabajo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='historialmovimientos',
            name='staff_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones_realizadas', to='panaderia.staffpanaderia'),
        ),
    ]
