# Generated by Django 5.0.14 on 2026-03-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0002_staffpanaderia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientefidelidad',
            name='requiere_cambio_pin',
            field=models.BooleanField(default=False, help_text='Bloquea movimientos hasta que el usuario actualice su contraseña temporal'),
        ),
    ]
