# Generated by Django 5.0.14 on 2026-03-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0003_clientefidelidad_requiere_cambio_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientefidelidad',
            name='activo',
            field=models.BooleanField(default=True, help_text='Baja lógica (Soft-Delete)'),
        ),
        migrations.AlterField(
            model_name='clientefidelidad',
            name='telefono',
            field=models.CharField(help_text='Para buscar rápido en caja', max_length=20),
        ),
    ]
