# Generated by Django 5.0.14 on 2026-03-04 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.AddField(
            model_name='cargaviaje',
            name='almacen_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flores.almacen'),
        ),
        migrations.CreateModel(
            name='StockAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='flores.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flores.producto')),
            ],
            options={
                'verbose_name': 'Stock en Almacén',
                'verbose_name_plural': 'Stocks en Almacenes',
                'unique_together': {('almacen', 'producto')},
            },
        ),
    ]
